[versions]
kotlin = "1.9.23"

pgt = "0.6.5"
shadow = "8.1.1"
blossom = "1.3.2"

mixinextras = "0.4.0"

[libraries]
mixinextras = { module = "io.github.llamalad7:mixinextras-fabric", version.ref = "mixinextras" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

pgt-main = { id = "org.polyfrost.multi-version", version.ref = "pgt" }
pgt-root = { id = "org.polyfrost.multi-version.root", version.ref = "pgt" }
pgt-default = { id = "org.polyfrost.defaults", version.ref = "pgt" }
pgt-defaults-repo = { id = "org.polyfrost.defaults.repo", version.ref = "pgt" }
pgt-defaults-loom = { id = "org.polyfrost.defaults.loom", version.ref = "pgt" }
pgt-defaults-java = { id = "org.polyfrost.defaults.java", version.ref = "pgt" }

shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
blossom = { id = "net.kyori.blossom", version.ref = "blossom" }